services:
  db:
    container_name: txDb
    image: postgres
    restart: always
    env_file:
      - postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  transactions-api:
    container_name: transactions-api
    build: ./src/TxTracker.TransactionsApi
    env_file:
      - TransactionsApi.env

    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: